# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    default_bus: "query"
    commandbus:
        command:
            method_inflector: tactician.handler.method_name_inflector.invoke
            middleware:
                - tactician.middleware.command_handler
        query:
            method_inflector: tactician.handler.method_name_inflector.invoke
            middleware:
                - tactician.middleware.command_handler

