networks:
  default:
    name: beta-readers-network

services:
  webserver:
    container_name: 'beta-readers-api-webserver'
    build:
      context: .docker/webserver
      args:
        PHP_VERSION: ${PHP_VERSION}
        HOST_UID: ${CURRENT_UID}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8000:80"
    links:
      - mysql
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - PHP_VERSION=${PHP_VERSION}
      - HOST_UID=${CURRENT_UID}
      - HOST_GROUP=${CURRENT_GROUP}
    volumes:
      - ./:/var/www/html
      - ./.docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/config/vhosts:/etc/apache2/sites-enabled
      - ./var/log/docker/apache2:/var/log/apache2
      - ./var/log/docker/xdebug:/var/log/xdebug
  mysql:
    container_name: 'beta-readers-mysql-8'
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        BASE_DIRECTORY: ${BASE_DIRECTORY}
    ports:
      - "3306:3306"
    volumes:
      - $PWD/.docker/mysql/template/config:/etc/mysql/conf.d
    env_file:
      - $PWD/.docker/mysql/template/env/common.env
    tmpfs:
      - /var/lib/mysql:rw,noexec,size=256M
    healthcheck:
      test: [ "CMD", "mysqladmin", "-umaster_user", "-pcan_all", "ping", "--silent" ]
      interval: 10s
      timeout: 7s
      retries: 10
      start_period: 0s