# Shared infrastructure components DI register
services:
  # Command and Query bus DI setup
  BetaReaders\Shared\Infrastructure\Bus\Command\TacticianSyncCommandBus:
    arguments:
      $bus: '@tactician.commandbus.command'

  BetaReaders\Shared\Infrastructure\Bus\Query\TacticianSyncQueryBus:
    arguments:
      $bus: '@tactician.commandbus.query'

  BetaReaders\Shared\Domain\Bus\Command\CommandBus: '@BetaReaders\Shared\Infrastructure\Bus\Command\TacticianSyncCommandBus'
  BetaReaders\Shared\Domain\Bus\Query\QueryBus: '@BetaReaders\Shared\Infrastructure\Bus\Query\TacticianSyncQueryBus'

  # AddJsonBodyToRequestListener
  BetaReaders\Packages\Symfony\Listener\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  # ExceptionListener
  BetaReaders\Packages\Symfony\Listener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  # UuidProvider
  BetaReaders\Shared\Infrastructure\Uid\RandomUuidProvider: ~
  BetaReaders\Shared\Domain\Uid\UuidProvider: '@BetaReaders\Shared\Infrastructure\Uid\RandomUuidProvider'

  # UlidProvider
  BetaReaders\Shared\Infrastructure\Uid\RandomUlidProvider: ~
  BetaReaders\Shared\Domain\Uid\UlidProvider: '@BetaReaders\Shared\Infrastructure\Uid\RandomUlidProvider'