services:
  BetaReaders\Module\User\Domain\UserRegisterer:
    arguments:
      $passwordHasher: '@BetaReaders\Module\User\Infrastructure\Password\SymfonyPasswordHasher'
      $repository: '@BetaReaders\Module\User\Infrastructure\Persistence\Doctrine\DoctrineUserRepository'