services:
  BetaReaders\Module\User\Infrastructure\Persistence\Doctrine\DoctrineUserRepository:
    parent: BetaReaders\Shared\Infrastructure\Doctrine\Repository

  beta_readers.users.http.json_body_guard:
    class: BetaReaders\Shared\Infrastructure\Validation\JsonSchema\JsonSchemaGuard
    arguments:
      $filesystem: '@filesystem'
      $schemasRootPath: '%user_module_json_schemas_base_path%'
      $formatter: '@BetaReaders\Shared\Infrastructure\Validation\JsonSchema\JsonSchemaErrorFormatter'

  beta_readers.users.http.json_api_controller:
    class: BetaReaders\Shared\Infrastructure\Entrypoint\Http\JsonApiController
    arguments:
      $queryBus: '@BetaReaders\Shared\Infrastructure\Bus\Query\TacticianSyncQueryBus'
      $commandBus: '@BetaReaders\Shared\Infrastructure\Bus\Command\TacticianSyncCommandBus'
      $bodyGuard: '@beta_readers.users.http.json_body_guard'
      $exceptionHandler: '@BetaReaders\Shared\Infrastructure\Entrypoint\Http\HttpExceptionsHandler'

  BetaReaders\Module\User\Infrastructure\Response\JsonApi\UserJsonApiSchemaRegisterer:
    tags:
      - { name: beta_readers.json_api_schema_registerer }

  BetaReaders\Packages\Symfony\Security\SymfonyPasswordAuthenticatedUserFactory: ~

  BetaReaders\Module\User\Infrastructure\Password\SymfonyPasswordHasher:
    arguments:
      $factory: '@BetaReaders\Packages\Symfony\Security\SymfonyPasswordAuthenticatedUserFactory'
      $hasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

  BetaReaders\Module\User\Infrastructure\UI\Controller\RegisterUserController:
    parent: beta_readers.users.http.json_api_controller
    public: true
    autowire: true
    tags:
      - controller.service_arguments