services:
  beta_readers.users.http.json_body_guard:
    class: BetaReaders\Shared\Infrastructure\Validation\JsonSchema\JsonSchemaGuard
    arguments:
      $schemasRootPath: '%user_module_json_schemas_base_path%'
      $filesystem: '@filesystem'

  BetaReaders\Packages\Symfony\Security\SymfonyPasswordAuthenticatedUserFactory: ~

  BetaReaders\Module\User\Infrastructure\Password\SymfonyPasswordHasher:
    arguments:
      $factory: '@BetaReaders\Packages\Symfony\Security\SymfonyPasswordAuthenticatedUserFactory'
      $hasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

  BetaReaders\Module\User\Infrastructure\UI\Controller\RegisterUserController:
    public: true
    autowire: true
    tags:
      - controller.service_arguments
    arguments:
      $bodyGuard: '@beta_readers.users.http.json_body_guard'
      $bus: '@BetaReaders\Shared\Infrastructure\Bus\Command\TacticianSyncCommandBus'

  BetaReaders\Module\User\Infrastructure\Persistence\Doctrine\DoctrineUserRepository:
    parent: BetaReaders\Shared\Infrastructure\Doctrine\Repository