system_routing:
    resource: '../src/Module/System/Infrastructure/DependencyInjection/routes.yaml'

users_routing:
    prefix: /api
    resource: '../src/Module/User/Infrastructure/DependencyInjection/routes.yaml'
