imports:
    - { resource: 'modules.yaml' }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    BetaReaders\:
        resource: '../src/'
        exclude:
            - '../src/Module/'
            - '../src/Shared/'
            - '../src/Packages/'
            - '../src/Kernel.php'
